<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/dbcoin-logo.ico" />

    <!-- Preconnect to Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />

    <!-- Load Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
      rel="stylesheet"
    />

    <title>DB Coin - Cryptocurrency</title>
    <meta
      name="description"
      content="DB Coin - The future of decentralized finance, built for the people."
    />

    <!-- Open Graph Meta Tags -->
    <meta property="og:title" content="DB Coin - Cryptocurrency" />
    <meta
      property="og:description"
      content="DB Coin - The future of decentralized finance, built for the people."
    />
    <meta property="og:image" content="/dbcoin-banner.jpg" />
    <meta property="og:url" content="/" />
    <meta property="og:type" content="website" />

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="DB Coin - Cryptocurrency" />
    <meta
      name="twitter:description"
      content="DB Coin - The future of decentralized finance, built for the people."
    />
    <meta name="twitter:image" content="/dbcoin-banner.jpg" />

    <!-- Preload Image -->
    <link rel="preload" fetchpriority="high" as="image" href="./dbcoin-logo.webp" type="image/webp" />

    <style>
      body {
        margin: 0;
        background-color: #0d1117;
        color: #e6edf3;
        padding: 0;
        font-family: 'Inter', sans-serif;
      }
      .preloader {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100vw;
        height: 100vh;
      }
      .img {
        margin: auto;
        max-width: 80%;
      }
    </style>
  </head>
  <body>
    <div id="root">
      <div class="preloader">
        <img class="img" src="./dbcoin-logo.webp" alt="DB Coin logo" />
      </div>
    </div>

    <script src="./scripts/calculate-height.js" defer></script>
  </body>
</html>
